apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: registry.uniproject.jp/infra/event-manager:0.1.7
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: app-secret
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: TZ
              value: Asia/Tokyo
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            periodSeconds: 30
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            periodSeconds: 30
            failureThreshold: 5
          startupProbe:
            httpGet:
              path: /api/health
              port: 3000
            failureThreshold: 30
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m # 必要最低限の0.1CPUを確保
              memory: 256Mi # 必要最低限の256MiBを確保
            limits:
              cpu: 300m # 最大0.3CPUまで使用可能
              memory: 512Mi # 最大512MiBまで使用可能
      imagePullSecrets:
        - name: internal-harbor
---
apiVersion: v1
kind: Service
metadata:
  name: app
spec:
  selector:
    app: app
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: ClusterIP
